apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic
  namespace: dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: petclinic
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
